#!/bin/sh
# `/sbin/setuser memcache` runs the given command as the user `memcache`.
# If you omit that part, the command will be run as root.
exec /sbin/setuser www-data /usr/bin/cashierd >>/var/log/cashierd.log 2>&1
