#!/bin/sh
# `/sbin/setuser memcache` runs the given command as the user `memcache`.
# If you omit that part, the command will be run as root.
cd /cashier

/usr/bin/cashierd >>/var/log/cashierd.log 2>&1
